// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// AuthorizationCode is the predicate function for authorizationcode builders.
type AuthorizationCode func(*sql.Selector)

// ServiceProvider is the predicate function for serviceprovider builders.
type ServiceProvider func(*sql.Selector)

// WhiteList is the predicate function for whitelist builders.
type WhiteList func(*sql.Selector)
