// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ochanoco/proxy/ent/servicelog"
)

// ServiceLogCreate is the builder for creating a ServiceLog entity.
type ServiceLogCreate struct {
	config
	mutation *ServiceLogMutation
	hooks    []Hook
}

// SetHeaders sets the "headers" field.
func (slc *ServiceLogCreate) SetHeaders(s string) *ServiceLogCreate {
	slc.mutation.SetHeaders(s)
	return slc
}

// SetBody sets the "body" field.
func (slc *ServiceLogCreate) SetBody(b []byte) *ServiceLogCreate {
	slc.mutation.SetBody(b)
	return slc
}

// Mutation returns the ServiceLogMutation object of the builder.
func (slc *ServiceLogCreate) Mutation() *ServiceLogMutation {
	return slc.mutation
}

// Save creates the ServiceLog in the database.
func (slc *ServiceLogCreate) Save(ctx context.Context) (*ServiceLog, error) {
	var (
		err  error
		node *ServiceLog
	)
	if len(slc.hooks) == 0 {
		if err = slc.check(); err != nil {
			return nil, err
		}
		node, err = slc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ServiceLogMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = slc.check(); err != nil {
				return nil, err
			}
			slc.mutation = mutation
			if node, err = slc.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(slc.hooks) - 1; i >= 0; i-- {
			if slc.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = slc.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, slc.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*ServiceLog)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from ServiceLogMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (slc *ServiceLogCreate) SaveX(ctx context.Context) *ServiceLog {
	v, err := slc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (slc *ServiceLogCreate) Exec(ctx context.Context) error {
	_, err := slc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (slc *ServiceLogCreate) ExecX(ctx context.Context) {
	if err := slc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (slc *ServiceLogCreate) check() error {
	if _, ok := slc.mutation.Headers(); !ok {
		return &ValidationError{Name: "headers", err: errors.New(`ent: missing required field "ServiceLog.headers"`)}
	}
	return nil
}

func (slc *ServiceLogCreate) sqlSave(ctx context.Context) (*ServiceLog, error) {
	_node, _spec := slc.createSpec()
	if err := sqlgraph.CreateNode(ctx, slc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	return _node, nil
}

func (slc *ServiceLogCreate) createSpec() (*ServiceLog, *sqlgraph.CreateSpec) {
	var (
		_node = &ServiceLog{config: slc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: servicelog.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: servicelog.FieldID,
			},
		}
	)
	if value, ok := slc.mutation.Headers(); ok {
		_spec.SetField(servicelog.FieldHeaders, field.TypeString, value)
		_node.Headers = value
	}
	if value, ok := slc.mutation.Body(); ok {
		_spec.SetField(servicelog.FieldBody, field.TypeBytes, value)
		_node.Body = value
	}
	return _node, _spec
}

// ServiceLogCreateBulk is the builder for creating many ServiceLog entities in bulk.
type ServiceLogCreateBulk struct {
	config
	builders []*ServiceLogCreate
}

// Save creates the ServiceLog entities in the database.
func (slcb *ServiceLogCreateBulk) Save(ctx context.Context) ([]*ServiceLog, error) {
	specs := make([]*sqlgraph.CreateSpec, len(slcb.builders))
	nodes := make([]*ServiceLog, len(slcb.builders))
	mutators := make([]Mutator, len(slcb.builders))
	for i := range slcb.builders {
		func(i int, root context.Context) {
			builder := slcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ServiceLogMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, slcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, slcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, slcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (slcb *ServiceLogCreateBulk) SaveX(ctx context.Context) []*ServiceLog {
	v, err := slcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (slcb *ServiceLogCreateBulk) Exec(ctx context.Context) error {
	_, err := slcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (slcb *ServiceLogCreateBulk) ExecX(ctx context.Context) {
	if err := slcb.Exec(ctx); err != nil {
		panic(err)
	}
}
