// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ochanoco/proxy/ent/predicate"
	"github.com/ochanoco/proxy/ent/servicelog"
)

// ServiceLogDelete is the builder for deleting a ServiceLog entity.
type ServiceLogDelete struct {
	config
	hooks    []Hook
	mutation *ServiceLogMutation
}

// Where appends a list predicates to the ServiceLogDelete builder.
func (sld *ServiceLogDelete) Where(ps ...predicate.ServiceLog) *ServiceLogDelete {
	sld.mutation.Where(ps...)
	return sld
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (sld *ServiceLogDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(sld.hooks) == 0 {
		affected, err = sld.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*ServiceLogMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			sld.mutation = mutation
			affected, err = sld.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(sld.hooks) - 1; i >= 0; i-- {
			if sld.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = sld.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, sld.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (sld *ServiceLogDelete) ExecX(ctx context.Context) int {
	n, err := sld.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (sld *ServiceLogDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: servicelog.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: servicelog.FieldID,
			},
		},
	}
	if ps := sld.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, sld.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	return affected, err
}

// ServiceLogDeleteOne is the builder for deleting a single ServiceLog entity.
type ServiceLogDeleteOne struct {
	sld *ServiceLogDelete
}

// Exec executes the deletion query.
func (sldo *ServiceLogDeleteOne) Exec(ctx context.Context) error {
	n, err := sldo.sld.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{servicelog.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (sldo *ServiceLogDeleteOne) ExecX(ctx context.Context) {
	sldo.sld.ExecX(ctx)
}
