// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ServiceProvidersColumns holds the columns for the "service_providers" table.
	ServiceProvidersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "host", Type: field.TypeString},
		{Name: "destination_ip", Type: field.TypeString},
	}
	// ServiceProvidersTable holds the schema information for the "service_providers" table.
	ServiceProvidersTable = &schema.Table{
		Name:       "service_providers",
		Columns:    ServiceProvidersColumns,
		PrimaryKey: []*schema.Column{ServiceProvidersColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "serviceprovider_host",
				Unique:  true,
				Columns: []*schema.Column{ServiceProvidersColumns[1]},
			},
		},
	}
	// WhiteListsColumns holds the columns for the "white_lists" table.
	WhiteListsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "path", Type: field.TypeString},
		{Name: "service_provider_whitelists", Type: field.TypeInt, Nullable: true},
	}
	// WhiteListsTable holds the schema information for the "white_lists" table.
	WhiteListsTable = &schema.Table{
		Name:       "white_lists",
		Columns:    WhiteListsColumns,
		PrimaryKey: []*schema.Column{WhiteListsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "white_lists_service_providers_whitelists",
				Columns:    []*schema.Column{WhiteListsColumns[2]},
				RefColumns: []*schema.Column{ServiceProvidersColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ServiceProvidersTable,
		WhiteListsTable,
	}
)

func init() {
	WhiteListsTable.ForeignKeys[0].RefTable = ServiceProvidersTable
}
