// Code generated by ent, DO NOT EDIT.

package communicationlog

const (
	// Label holds the string label denoting the communicationlog type in the database.
	Label = "communication_log"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldType holds the string denoting the type field in the database.
	FieldType = "type"
	// FieldTime holds the string denoting the time field in the database.
	FieldTime = "time"
	// FieldHeaders holds the string denoting the headers field in the database.
	FieldHeaders = "headers"
	// FieldBody holds the string denoting the body field in the database.
	FieldBody = "body"
	// Table holds the table name of the communicationlog in the database.
	Table = "communication_logs"
)

// Columns holds all SQL columns for communicationlog fields.
var Columns = []string{
	FieldID,
	FieldType,
	FieldTime,
	FieldHeaders,
	FieldBody,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
