// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ochanoco/proxy/ent/predicate"
	"github.com/ochanoco/proxy/ent/serviceprovider"
	"github.com/ochanoco/proxy/ent/whitelist"
)

// WhiteListQuery is the builder for querying WhiteList entities.
type WhiteListQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.WhiteList
	// eager-loading edges.
	withOwner *ServiceProviderQuery
	withFKs   bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the WhiteListQuery builder.
func (wlq *WhiteListQuery) Where(ps ...predicate.WhiteList) *WhiteListQuery {
	wlq.predicates = append(wlq.predicates, ps...)
	return wlq
}

// Limit adds a limit step to the query.
func (wlq *WhiteListQuery) Limit(limit int) *WhiteListQuery {
	wlq.limit = &limit
	return wlq
}

// Offset adds an offset step to the query.
func (wlq *WhiteListQuery) Offset(offset int) *WhiteListQuery {
	wlq.offset = &offset
	return wlq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (wlq *WhiteListQuery) Unique(unique bool) *WhiteListQuery {
	wlq.unique = &unique
	return wlq
}

// Order adds an order step to the query.
func (wlq *WhiteListQuery) Order(o ...OrderFunc) *WhiteListQuery {
	wlq.order = append(wlq.order, o...)
	return wlq
}

// QueryOwner chains the current query on the "owner" edge.
func (wlq *WhiteListQuery) QueryOwner() *ServiceProviderQuery {
	query := &ServiceProviderQuery{config: wlq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := wlq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := wlq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(whitelist.Table, whitelist.FieldID, selector),
			sqlgraph.To(serviceprovider.Table, serviceprovider.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, whitelist.OwnerTable, whitelist.OwnerColumn),
		)
		fromU = sqlgraph.SetNeighbors(wlq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first WhiteList entity from the query.
// Returns a *NotFoundError when no WhiteList was found.
func (wlq *WhiteListQuery) First(ctx context.Context) (*WhiteList, error) {
	nodes, err := wlq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{whitelist.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (wlq *WhiteListQuery) FirstX(ctx context.Context) *WhiteList {
	node, err := wlq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first WhiteList ID from the query.
// Returns a *NotFoundError when no WhiteList ID was found.
func (wlq *WhiteListQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = wlq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{whitelist.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (wlq *WhiteListQuery) FirstIDX(ctx context.Context) int {
	id, err := wlq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single WhiteList entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one WhiteList entity is found.
// Returns a *NotFoundError when no WhiteList entities are found.
func (wlq *WhiteListQuery) Only(ctx context.Context) (*WhiteList, error) {
	nodes, err := wlq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{whitelist.Label}
	default:
		return nil, &NotSingularError{whitelist.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (wlq *WhiteListQuery) OnlyX(ctx context.Context) *WhiteList {
	node, err := wlq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only WhiteList ID in the query.
// Returns a *NotSingularError when more than one WhiteList ID is found.
// Returns a *NotFoundError when no entities are found.
func (wlq *WhiteListQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = wlq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{whitelist.Label}
	default:
		err = &NotSingularError{whitelist.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (wlq *WhiteListQuery) OnlyIDX(ctx context.Context) int {
	id, err := wlq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of WhiteLists.
func (wlq *WhiteListQuery) All(ctx context.Context) ([]*WhiteList, error) {
	if err := wlq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return wlq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (wlq *WhiteListQuery) AllX(ctx context.Context) []*WhiteList {
	nodes, err := wlq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of WhiteList IDs.
func (wlq *WhiteListQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := wlq.Select(whitelist.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (wlq *WhiteListQuery) IDsX(ctx context.Context) []int {
	ids, err := wlq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (wlq *WhiteListQuery) Count(ctx context.Context) (int, error) {
	if err := wlq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return wlq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (wlq *WhiteListQuery) CountX(ctx context.Context) int {
	count, err := wlq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (wlq *WhiteListQuery) Exist(ctx context.Context) (bool, error) {
	if err := wlq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return wlq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (wlq *WhiteListQuery) ExistX(ctx context.Context) bool {
	exist, err := wlq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the WhiteListQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (wlq *WhiteListQuery) Clone() *WhiteListQuery {
	if wlq == nil {
		return nil
	}
	return &WhiteListQuery{
		config:     wlq.config,
		limit:      wlq.limit,
		offset:     wlq.offset,
		order:      append([]OrderFunc{}, wlq.order...),
		predicates: append([]predicate.WhiteList{}, wlq.predicates...),
		withOwner:  wlq.withOwner.Clone(),
		// clone intermediate query.
		sql:    wlq.sql.Clone(),
		path:   wlq.path,
		unique: wlq.unique,
	}
}

// WithOwner tells the query-builder to eager-load the nodes that are connected to
// the "owner" edge. The optional arguments are used to configure the query builder of the edge.
func (wlq *WhiteListQuery) WithOwner(opts ...func(*ServiceProviderQuery)) *WhiteListQuery {
	query := &ServiceProviderQuery{config: wlq.config}
	for _, opt := range opts {
		opt(query)
	}
	wlq.withOwner = query
	return wlq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Path string `json:"path,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.WhiteList.Query().
//		GroupBy(whitelist.FieldPath).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (wlq *WhiteListQuery) GroupBy(field string, fields ...string) *WhiteListGroupBy {
	group := &WhiteListGroupBy{config: wlq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := wlq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return wlq.sqlQuery(ctx), nil
	}
	return group
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Path string `json:"path,omitempty"`
//	}
//
//	client.WhiteList.Query().
//		Select(whitelist.FieldPath).
//		Scan(ctx, &v)
func (wlq *WhiteListQuery) Select(fields ...string) *WhiteListSelect {
	wlq.fields = append(wlq.fields, fields...)
	return &WhiteListSelect{WhiteListQuery: wlq}
}

func (wlq *WhiteListQuery) prepareQuery(ctx context.Context) error {
	for _, f := range wlq.fields {
		if !whitelist.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if wlq.path != nil {
		prev, err := wlq.path(ctx)
		if err != nil {
			return err
		}
		wlq.sql = prev
	}
	return nil
}

func (wlq *WhiteListQuery) sqlAll(ctx context.Context) ([]*WhiteList, error) {
	var (
		nodes       = []*WhiteList{}
		withFKs     = wlq.withFKs
		_spec       = wlq.querySpec()
		loadedTypes = [1]bool{
			wlq.withOwner != nil,
		}
	)
	if wlq.withOwner != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, whitelist.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		node := &WhiteList{config: wlq.config}
		nodes = append(nodes, node)
		return node.scanValues(columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if err := sqlgraph.QueryNodes(ctx, wlq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}

	if query := wlq.withOwner; query != nil {
		ids := make([]int, 0, len(nodes))
		nodeids := make(map[int][]*WhiteList)
		for i := range nodes {
			if nodes[i].service_provider_whitelists == nil {
				continue
			}
			fk := *nodes[i].service_provider_whitelists
			if _, ok := nodeids[fk]; !ok {
				ids = append(ids, fk)
			}
			nodeids[fk] = append(nodeids[fk], nodes[i])
		}
		query.Where(serviceprovider.IDIn(ids...))
		neighbors, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, n := range neighbors {
			nodes, ok := nodeids[n.ID]
			if !ok {
				return nil, fmt.Errorf(`unexpected foreign-key "service_provider_whitelists" returned %v`, n.ID)
			}
			for i := range nodes {
				nodes[i].Edges.Owner = n
			}
		}
	}

	return nodes, nil
}

func (wlq *WhiteListQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := wlq.querySpec()
	_spec.Node.Columns = wlq.fields
	if len(wlq.fields) > 0 {
		_spec.Unique = wlq.unique != nil && *wlq.unique
	}
	return sqlgraph.CountNodes(ctx, wlq.driver, _spec)
}

func (wlq *WhiteListQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := wlq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (wlq *WhiteListQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   whitelist.Table,
			Columns: whitelist.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: whitelist.FieldID,
			},
		},
		From:   wlq.sql,
		Unique: true,
	}
	if unique := wlq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := wlq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, whitelist.FieldID)
		for i := range fields {
			if fields[i] != whitelist.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := wlq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := wlq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := wlq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := wlq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (wlq *WhiteListQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(wlq.driver.Dialect())
	t1 := builder.Table(whitelist.Table)
	columns := wlq.fields
	if len(columns) == 0 {
		columns = whitelist.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if wlq.sql != nil {
		selector = wlq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if wlq.unique != nil && *wlq.unique {
		selector.Distinct()
	}
	for _, p := range wlq.predicates {
		p(selector)
	}
	for _, p := range wlq.order {
		p(selector)
	}
	if offset := wlq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := wlq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// WhiteListGroupBy is the group-by builder for WhiteList entities.
type WhiteListGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (wlgb *WhiteListGroupBy) Aggregate(fns ...AggregateFunc) *WhiteListGroupBy {
	wlgb.fns = append(wlgb.fns, fns...)
	return wlgb
}

// Scan applies the group-by query and scans the result into the given value.
func (wlgb *WhiteListGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := wlgb.path(ctx)
	if err != nil {
		return err
	}
	wlgb.sql = query
	return wlgb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (wlgb *WhiteListGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := wlgb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by.
// It is only allowed when executing a group-by query with one field.
func (wlgb *WhiteListGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(wlgb.fields) > 1 {
		return nil, errors.New("ent: WhiteListGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := wlgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (wlgb *WhiteListGroupBy) StringsX(ctx context.Context) []string {
	v, err := wlgb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (wlgb *WhiteListGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = wlgb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{whitelist.Label}
	default:
		err = fmt.Errorf("ent: WhiteListGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (wlgb *WhiteListGroupBy) StringX(ctx context.Context) string {
	v, err := wlgb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by.
// It is only allowed when executing a group-by query with one field.
func (wlgb *WhiteListGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(wlgb.fields) > 1 {
		return nil, errors.New("ent: WhiteListGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := wlgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (wlgb *WhiteListGroupBy) IntsX(ctx context.Context) []int {
	v, err := wlgb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (wlgb *WhiteListGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = wlgb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{whitelist.Label}
	default:
		err = fmt.Errorf("ent: WhiteListGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (wlgb *WhiteListGroupBy) IntX(ctx context.Context) int {
	v, err := wlgb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by.
// It is only allowed when executing a group-by query with one field.
func (wlgb *WhiteListGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(wlgb.fields) > 1 {
		return nil, errors.New("ent: WhiteListGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := wlgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (wlgb *WhiteListGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := wlgb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (wlgb *WhiteListGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = wlgb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{whitelist.Label}
	default:
		err = fmt.Errorf("ent: WhiteListGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (wlgb *WhiteListGroupBy) Float64X(ctx context.Context) float64 {
	v, err := wlgb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by.
// It is only allowed when executing a group-by query with one field.
func (wlgb *WhiteListGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(wlgb.fields) > 1 {
		return nil, errors.New("ent: WhiteListGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := wlgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (wlgb *WhiteListGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := wlgb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (wlgb *WhiteListGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = wlgb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{whitelist.Label}
	default:
		err = fmt.Errorf("ent: WhiteListGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (wlgb *WhiteListGroupBy) BoolX(ctx context.Context) bool {
	v, err := wlgb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (wlgb *WhiteListGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range wlgb.fields {
		if !whitelist.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := wlgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := wlgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (wlgb *WhiteListGroupBy) sqlQuery() *sql.Selector {
	selector := wlgb.sql.Select()
	aggregation := make([]string, 0, len(wlgb.fns))
	for _, fn := range wlgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(wlgb.fields)+len(wlgb.fns))
		for _, f := range wlgb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(wlgb.fields...)...)
}

// WhiteListSelect is the builder for selecting fields of WhiteList entities.
type WhiteListSelect struct {
	*WhiteListQuery
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (wls *WhiteListSelect) Scan(ctx context.Context, v interface{}) error {
	if err := wls.prepareQuery(ctx); err != nil {
		return err
	}
	wls.sql = wls.WhiteListQuery.sqlQuery(ctx)
	return wls.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (wls *WhiteListSelect) ScanX(ctx context.Context, v interface{}) {
	if err := wls.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from a selector. It is only allowed when selecting one field.
func (wls *WhiteListSelect) Strings(ctx context.Context) ([]string, error) {
	if len(wls.fields) > 1 {
		return nil, errors.New("ent: WhiteListSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := wls.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (wls *WhiteListSelect) StringsX(ctx context.Context) []string {
	v, err := wls.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a selector. It is only allowed when selecting one field.
func (wls *WhiteListSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = wls.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{whitelist.Label}
	default:
		err = fmt.Errorf("ent: WhiteListSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (wls *WhiteListSelect) StringX(ctx context.Context) string {
	v, err := wls.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from a selector. It is only allowed when selecting one field.
func (wls *WhiteListSelect) Ints(ctx context.Context) ([]int, error) {
	if len(wls.fields) > 1 {
		return nil, errors.New("ent: WhiteListSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := wls.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (wls *WhiteListSelect) IntsX(ctx context.Context) []int {
	v, err := wls.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a selector. It is only allowed when selecting one field.
func (wls *WhiteListSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = wls.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{whitelist.Label}
	default:
		err = fmt.Errorf("ent: WhiteListSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (wls *WhiteListSelect) IntX(ctx context.Context) int {
	v, err := wls.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from a selector. It is only allowed when selecting one field.
func (wls *WhiteListSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(wls.fields) > 1 {
		return nil, errors.New("ent: WhiteListSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := wls.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (wls *WhiteListSelect) Float64sX(ctx context.Context) []float64 {
	v, err := wls.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a selector. It is only allowed when selecting one field.
func (wls *WhiteListSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = wls.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{whitelist.Label}
	default:
		err = fmt.Errorf("ent: WhiteListSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (wls *WhiteListSelect) Float64X(ctx context.Context) float64 {
	v, err := wls.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from a selector. It is only allowed when selecting one field.
func (wls *WhiteListSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(wls.fields) > 1 {
		return nil, errors.New("ent: WhiteListSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := wls.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (wls *WhiteListSelect) BoolsX(ctx context.Context) []bool {
	v, err := wls.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a selector. It is only allowed when selecting one field.
func (wls *WhiteListSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = wls.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{whitelist.Label}
	default:
		err = fmt.Errorf("ent: WhiteListSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (wls *WhiteListSelect) BoolX(ctx context.Context) bool {
	v, err := wls.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (wls *WhiteListSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := wls.sql.Query()
	if err := wls.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
