// Code generated by entc, DO NOT EDIT.

package project

const (
	// Label holds the string label denoting the project type in the database.
	Label = "project"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldDomain holds the string denoting the domain field in the database.
	FieldDomain = "domain"
	// FieldDestination holds the string denoting the destination field in the database.
	FieldDestination = "destination"
	// FieldLineID holds the string denoting the line_id field in the database.
	FieldLineID = "line_id"
	// EdgeWhitelists holds the string denoting the whitelists edge name in mutations.
	EdgeWhitelists = "whitelists"
	// Table holds the table name of the project in the database.
	Table = "projects"
	// WhitelistsTable is the table that holds the whitelists relation/edge.
	WhitelistsTable = "white_lists"
	// WhitelistsInverseTable is the table name for the WhiteList entity.
	// It exists in this package in order to avoid circular dependency with the "whitelist" package.
	WhitelistsInverseTable = "white_lists"
	// WhitelistsColumn is the table column denoting the whitelists relation/edge.
	WhitelistsColumn = "project_whitelists"
)

// Columns holds all SQL columns for project fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldDomain,
	FieldDestination,
	FieldLineID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
