// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// CommunicationLogsColumns holds the columns for the "communication_logs" table.
	CommunicationLogsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "type", Type: field.TypeString},
		{Name: "time", Type: field.TypeTime},
		{Name: "headers", Type: field.TypeString},
		{Name: "body", Type: field.TypeBytes, Nullable: true},
	}
	// CommunicationLogsTable holds the schema information for the "communication_logs" table.
	CommunicationLogsTable = &schema.Table{
		Name:       "communication_logs",
		Columns:    CommunicationLogsColumns,
		PrimaryKey: []*schema.Column{CommunicationLogsColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		CommunicationLogsTable,
	}
)

func init() {
}
