// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ServiceProvidersColumns holds the columns for the "service_providers" table.
	ServiceProvidersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "host", Type: field.TypeString},
		{Name: "destination", Type: field.TypeString},
	}
	// ServiceProvidersTable holds the schema information for the "service_providers" table.
	ServiceProvidersTable = &schema.Table{
		Name:       "service_providers",
		Columns:    ServiceProvidersColumns,
		PrimaryKey: []*schema.Column{ServiceProvidersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ServiceProvidersTable,
	}
)

func init() {
}
