// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ochanoco/proxy/ent/authorizationcode"
	"github.com/ochanoco/proxy/ent/predicate"
	"github.com/ochanoco/proxy/ent/serviceprovider"
)

// AuthorizationCodeUpdate is the builder for updating AuthorizationCode entities.
type AuthorizationCodeUpdate struct {
	config
	hooks    []Hook
	mutation *AuthorizationCodeMutation
}

// Where appends a list predicates to the AuthorizationCodeUpdate builder.
func (acu *AuthorizationCodeUpdate) Where(ps ...predicate.AuthorizationCode) *AuthorizationCodeUpdate {
	acu.mutation.Where(ps...)
	return acu
}

// SetToken sets the "token" field.
func (acu *AuthorizationCodeUpdate) SetToken(s string) *AuthorizationCodeUpdate {
	acu.mutation.SetToken(s)
	return acu
}

// SetOwnerID sets the "owner" edge to the ServiceProvider entity by ID.
func (acu *AuthorizationCodeUpdate) SetOwnerID(id int) *AuthorizationCodeUpdate {
	acu.mutation.SetOwnerID(id)
	return acu
}

// SetNillableOwnerID sets the "owner" edge to the ServiceProvider entity by ID if the given value is not nil.
func (acu *AuthorizationCodeUpdate) SetNillableOwnerID(id *int) *AuthorizationCodeUpdate {
	if id != nil {
		acu = acu.SetOwnerID(*id)
	}
	return acu
}

// SetOwner sets the "owner" edge to the ServiceProvider entity.
func (acu *AuthorizationCodeUpdate) SetOwner(s *ServiceProvider) *AuthorizationCodeUpdate {
	return acu.SetOwnerID(s.ID)
}

// Mutation returns the AuthorizationCodeMutation object of the builder.
func (acu *AuthorizationCodeUpdate) Mutation() *AuthorizationCodeMutation {
	return acu.mutation
}

// ClearOwner clears the "owner" edge to the ServiceProvider entity.
func (acu *AuthorizationCodeUpdate) ClearOwner() *AuthorizationCodeUpdate {
	acu.mutation.ClearOwner()
	return acu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (acu *AuthorizationCodeUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(acu.hooks) == 0 {
		affected, err = acu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*AuthorizationCodeMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			acu.mutation = mutation
			affected, err = acu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(acu.hooks) - 1; i >= 0; i-- {
			if acu.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = acu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, acu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (acu *AuthorizationCodeUpdate) SaveX(ctx context.Context) int {
	affected, err := acu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (acu *AuthorizationCodeUpdate) Exec(ctx context.Context) error {
	_, err := acu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (acu *AuthorizationCodeUpdate) ExecX(ctx context.Context) {
	if err := acu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (acu *AuthorizationCodeUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   authorizationcode.Table,
			Columns: authorizationcode.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: authorizationcode.FieldID,
			},
		},
	}
	if ps := acu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := acu.mutation.Token(); ok {
		_spec.SetField(authorizationcode.FieldToken, field.TypeString, value)
	}
	if acu.mutation.OwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   authorizationcode.OwnerTable,
			Columns: []string{authorizationcode.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: serviceprovider.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := acu.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   authorizationcode.OwnerTable,
			Columns: []string{authorizationcode.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: serviceprovider.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, acu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{authorizationcode.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	return n, nil
}

// AuthorizationCodeUpdateOne is the builder for updating a single AuthorizationCode entity.
type AuthorizationCodeUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AuthorizationCodeMutation
}

// SetToken sets the "token" field.
func (acuo *AuthorizationCodeUpdateOne) SetToken(s string) *AuthorizationCodeUpdateOne {
	acuo.mutation.SetToken(s)
	return acuo
}

// SetOwnerID sets the "owner" edge to the ServiceProvider entity by ID.
func (acuo *AuthorizationCodeUpdateOne) SetOwnerID(id int) *AuthorizationCodeUpdateOne {
	acuo.mutation.SetOwnerID(id)
	return acuo
}

// SetNillableOwnerID sets the "owner" edge to the ServiceProvider entity by ID if the given value is not nil.
func (acuo *AuthorizationCodeUpdateOne) SetNillableOwnerID(id *int) *AuthorizationCodeUpdateOne {
	if id != nil {
		acuo = acuo.SetOwnerID(*id)
	}
	return acuo
}

// SetOwner sets the "owner" edge to the ServiceProvider entity.
func (acuo *AuthorizationCodeUpdateOne) SetOwner(s *ServiceProvider) *AuthorizationCodeUpdateOne {
	return acuo.SetOwnerID(s.ID)
}

// Mutation returns the AuthorizationCodeMutation object of the builder.
func (acuo *AuthorizationCodeUpdateOne) Mutation() *AuthorizationCodeMutation {
	return acuo.mutation
}

// ClearOwner clears the "owner" edge to the ServiceProvider entity.
func (acuo *AuthorizationCodeUpdateOne) ClearOwner() *AuthorizationCodeUpdateOne {
	acuo.mutation.ClearOwner()
	return acuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (acuo *AuthorizationCodeUpdateOne) Select(field string, fields ...string) *AuthorizationCodeUpdateOne {
	acuo.fields = append([]string{field}, fields...)
	return acuo
}

// Save executes the query and returns the updated AuthorizationCode entity.
func (acuo *AuthorizationCodeUpdateOne) Save(ctx context.Context) (*AuthorizationCode, error) {
	var (
		err  error
		node *AuthorizationCode
	)
	if len(acuo.hooks) == 0 {
		node, err = acuo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*AuthorizationCodeMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			acuo.mutation = mutation
			node, err = acuo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(acuo.hooks) - 1; i >= 0; i-- {
			if acuo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = acuo.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, acuo.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*AuthorizationCode)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from AuthorizationCodeMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (acuo *AuthorizationCodeUpdateOne) SaveX(ctx context.Context) *AuthorizationCode {
	node, err := acuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (acuo *AuthorizationCodeUpdateOne) Exec(ctx context.Context) error {
	_, err := acuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (acuo *AuthorizationCodeUpdateOne) ExecX(ctx context.Context) {
	if err := acuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (acuo *AuthorizationCodeUpdateOne) sqlSave(ctx context.Context) (_node *AuthorizationCode, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   authorizationcode.Table,
			Columns: authorizationcode.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: authorizationcode.FieldID,
			},
		},
	}
	id, ok := acuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AuthorizationCode.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := acuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, authorizationcode.FieldID)
		for _, f := range fields {
			if !authorizationcode.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != authorizationcode.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := acuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := acuo.mutation.Token(); ok {
		_spec.SetField(authorizationcode.FieldToken, field.TypeString, value)
	}
	if acuo.mutation.OwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   authorizationcode.OwnerTable,
			Columns: []string{authorizationcode.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: serviceprovider.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := acuo.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   authorizationcode.OwnerTable,
			Columns: []string{authorizationcode.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: serviceprovider.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &AuthorizationCode{config: acuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, acuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{authorizationcode.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	return _node, nil
}
