// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ochanoco/proxy/ent/communicationlog"
	"github.com/ochanoco/proxy/ent/predicate"
)

// CommunicationLogQuery is the builder for querying CommunicationLog entities.
type CommunicationLogQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.CommunicationLog
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the CommunicationLogQuery builder.
func (clq *CommunicationLogQuery) Where(ps ...predicate.CommunicationLog) *CommunicationLogQuery {
	clq.predicates = append(clq.predicates, ps...)
	return clq
}

// Limit adds a limit step to the query.
func (clq *CommunicationLogQuery) Limit(limit int) *CommunicationLogQuery {
	clq.limit = &limit
	return clq
}

// Offset adds an offset step to the query.
func (clq *CommunicationLogQuery) Offset(offset int) *CommunicationLogQuery {
	clq.offset = &offset
	return clq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (clq *CommunicationLogQuery) Unique(unique bool) *CommunicationLogQuery {
	clq.unique = &unique
	return clq
}

// Order adds an order step to the query.
func (clq *CommunicationLogQuery) Order(o ...OrderFunc) *CommunicationLogQuery {
	clq.order = append(clq.order, o...)
	return clq
}

// First returns the first CommunicationLog entity from the query.
// Returns a *NotFoundError when no CommunicationLog was found.
func (clq *CommunicationLogQuery) First(ctx context.Context) (*CommunicationLog, error) {
	nodes, err := clq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{communicationlog.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (clq *CommunicationLogQuery) FirstX(ctx context.Context) *CommunicationLog {
	node, err := clq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first CommunicationLog ID from the query.
// Returns a *NotFoundError when no CommunicationLog ID was found.
func (clq *CommunicationLogQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = clq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{communicationlog.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (clq *CommunicationLogQuery) FirstIDX(ctx context.Context) int {
	id, err := clq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single CommunicationLog entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one CommunicationLog entity is found.
// Returns a *NotFoundError when no CommunicationLog entities are found.
func (clq *CommunicationLogQuery) Only(ctx context.Context) (*CommunicationLog, error) {
	nodes, err := clq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{communicationlog.Label}
	default:
		return nil, &NotSingularError{communicationlog.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (clq *CommunicationLogQuery) OnlyX(ctx context.Context) *CommunicationLog {
	node, err := clq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only CommunicationLog ID in the query.
// Returns a *NotSingularError when more than one CommunicationLog ID is found.
// Returns a *NotFoundError when no entities are found.
func (clq *CommunicationLogQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = clq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{communicationlog.Label}
	default:
		err = &NotSingularError{communicationlog.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (clq *CommunicationLogQuery) OnlyIDX(ctx context.Context) int {
	id, err := clq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of CommunicationLogs.
func (clq *CommunicationLogQuery) All(ctx context.Context) ([]*CommunicationLog, error) {
	if err := clq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return clq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (clq *CommunicationLogQuery) AllX(ctx context.Context) []*CommunicationLog {
	nodes, err := clq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of CommunicationLog IDs.
func (clq *CommunicationLogQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := clq.Select(communicationlog.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (clq *CommunicationLogQuery) IDsX(ctx context.Context) []int {
	ids, err := clq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (clq *CommunicationLogQuery) Count(ctx context.Context) (int, error) {
	if err := clq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return clq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (clq *CommunicationLogQuery) CountX(ctx context.Context) int {
	count, err := clq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (clq *CommunicationLogQuery) Exist(ctx context.Context) (bool, error) {
	if err := clq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return clq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (clq *CommunicationLogQuery) ExistX(ctx context.Context) bool {
	exist, err := clq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the CommunicationLogQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (clq *CommunicationLogQuery) Clone() *CommunicationLogQuery {
	if clq == nil {
		return nil
	}
	return &CommunicationLogQuery{
		config:     clq.config,
		limit:      clq.limit,
		offset:     clq.offset,
		order:      append([]OrderFunc{}, clq.order...),
		predicates: append([]predicate.CommunicationLog{}, clq.predicates...),
		// clone intermediate query.
		sql:    clq.sql.Clone(),
		path:   clq.path,
		unique: clq.unique,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Type string `json:"type,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.CommunicationLog.Query().
//		GroupBy(communicationlog.FieldType).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (clq *CommunicationLogQuery) GroupBy(field string, fields ...string) *CommunicationLogGroupBy {
	grbuild := &CommunicationLogGroupBy{config: clq.config}
	grbuild.fields = append([]string{field}, fields...)
	grbuild.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := clq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return clq.sqlQuery(ctx), nil
	}
	grbuild.label = communicationlog.Label
	grbuild.flds, grbuild.scan = &grbuild.fields, grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Type string `json:"type,omitempty"`
//	}
//
//	client.CommunicationLog.Query().
//		Select(communicationlog.FieldType).
//		Scan(ctx, &v)
func (clq *CommunicationLogQuery) Select(fields ...string) *CommunicationLogSelect {
	clq.fields = append(clq.fields, fields...)
	selbuild := &CommunicationLogSelect{CommunicationLogQuery: clq}
	selbuild.label = communicationlog.Label
	selbuild.flds, selbuild.scan = &clq.fields, selbuild.Scan
	return selbuild
}

// Aggregate returns a CommunicationLogSelect configured with the given aggregations.
func (clq *CommunicationLogQuery) Aggregate(fns ...AggregateFunc) *CommunicationLogSelect {
	return clq.Select().Aggregate(fns...)
}

func (clq *CommunicationLogQuery) prepareQuery(ctx context.Context) error {
	for _, f := range clq.fields {
		if !communicationlog.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if clq.path != nil {
		prev, err := clq.path(ctx)
		if err != nil {
			return err
		}
		clq.sql = prev
	}
	return nil
}

func (clq *CommunicationLogQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*CommunicationLog, error) {
	var (
		nodes = []*CommunicationLog{}
		_spec = clq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*CommunicationLog).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &CommunicationLog{config: clq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, clq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (clq *CommunicationLogQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := clq.querySpec()
	_spec.Node.Columns = clq.fields
	if len(clq.fields) > 0 {
		_spec.Unique = clq.unique != nil && *clq.unique
	}
	return sqlgraph.CountNodes(ctx, clq.driver, _spec)
}

func (clq *CommunicationLogQuery) sqlExist(ctx context.Context) (bool, error) {
	switch _, err := clq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

func (clq *CommunicationLogQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   communicationlog.Table,
			Columns: communicationlog.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: communicationlog.FieldID,
			},
		},
		From:   clq.sql,
		Unique: true,
	}
	if unique := clq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := clq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, communicationlog.FieldID)
		for i := range fields {
			if fields[i] != communicationlog.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := clq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := clq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := clq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := clq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (clq *CommunicationLogQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(clq.driver.Dialect())
	t1 := builder.Table(communicationlog.Table)
	columns := clq.fields
	if len(columns) == 0 {
		columns = communicationlog.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if clq.sql != nil {
		selector = clq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if clq.unique != nil && *clq.unique {
		selector.Distinct()
	}
	for _, p := range clq.predicates {
		p(selector)
	}
	for _, p := range clq.order {
		p(selector)
	}
	if offset := clq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := clq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// CommunicationLogGroupBy is the group-by builder for CommunicationLog entities.
type CommunicationLogGroupBy struct {
	config
	selector
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (clgb *CommunicationLogGroupBy) Aggregate(fns ...AggregateFunc) *CommunicationLogGroupBy {
	clgb.fns = append(clgb.fns, fns...)
	return clgb
}

// Scan applies the group-by query and scans the result into the given value.
func (clgb *CommunicationLogGroupBy) Scan(ctx context.Context, v any) error {
	query, err := clgb.path(ctx)
	if err != nil {
		return err
	}
	clgb.sql = query
	return clgb.sqlScan(ctx, v)
}

func (clgb *CommunicationLogGroupBy) sqlScan(ctx context.Context, v any) error {
	for _, f := range clgb.fields {
		if !communicationlog.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := clgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := clgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (clgb *CommunicationLogGroupBy) sqlQuery() *sql.Selector {
	selector := clgb.sql.Select()
	aggregation := make([]string, 0, len(clgb.fns))
	for _, fn := range clgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(clgb.fields)+len(clgb.fns))
		for _, f := range clgb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(clgb.fields...)...)
}

// CommunicationLogSelect is the builder for selecting fields of CommunicationLog entities.
type CommunicationLogSelect struct {
	*CommunicationLogQuery
	selector
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (cls *CommunicationLogSelect) Aggregate(fns ...AggregateFunc) *CommunicationLogSelect {
	cls.fns = append(cls.fns, fns...)
	return cls
}

// Scan applies the selector query and scans the result into the given value.
func (cls *CommunicationLogSelect) Scan(ctx context.Context, v any) error {
	if err := cls.prepareQuery(ctx); err != nil {
		return err
	}
	cls.sql = cls.CommunicationLogQuery.sqlQuery(ctx)
	return cls.sqlScan(ctx, v)
}

func (cls *CommunicationLogSelect) sqlScan(ctx context.Context, v any) error {
	aggregation := make([]string, 0, len(cls.fns))
	for _, fn := range cls.fns {
		aggregation = append(aggregation, fn(cls.sql))
	}
	switch n := len(*cls.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		cls.sql.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		cls.sql.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := cls.sql.Query()
	if err := cls.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
