// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ochanoco/proxy/ent/communicationlog"
	"github.com/ochanoco/proxy/ent/predicate"
)

// CommunicationLogDelete is the builder for deleting a CommunicationLog entity.
type CommunicationLogDelete struct {
	config
	hooks    []Hook
	mutation *CommunicationLogMutation
}

// Where appends a list predicates to the CommunicationLogDelete builder.
func (cld *CommunicationLogDelete) Where(ps ...predicate.CommunicationLog) *CommunicationLogDelete {
	cld.mutation.Where(ps...)
	return cld
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (cld *CommunicationLogDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(cld.hooks) == 0 {
		affected, err = cld.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*CommunicationLogMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			cld.mutation = mutation
			affected, err = cld.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(cld.hooks) - 1; i >= 0; i-- {
			if cld.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = cld.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, cld.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (cld *CommunicationLogDelete) ExecX(ctx context.Context) int {
	n, err := cld.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (cld *CommunicationLogDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: communicationlog.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: communicationlog.FieldID,
			},
		},
	}
	if ps := cld.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, cld.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	return affected, err
}

// CommunicationLogDeleteOne is the builder for deleting a single CommunicationLog entity.
type CommunicationLogDeleteOne struct {
	cld *CommunicationLogDelete
}

// Exec executes the deletion query.
func (cldo *CommunicationLogDeleteOne) Exec(ctx context.Context) error {
	n, err := cldo.cld.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{communicationlog.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (cldo *CommunicationLogDeleteOne) ExecX(ctx context.Context) {
	cldo.cld.ExecX(ctx)
}
