// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/ochanoco/proxy/ent/requestlog"
)

// RequestLog is the model entity for the RequestLog schema.
type RequestLog struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Time holds the value of the "time" field.
	Time time.Time `json:"time,omitempty"`
	// Headers holds the value of the "headers" field.
	Headers string `json:"headers,omitempty"`
	// Body holds the value of the "body" field.
	Body []byte `json:"body,omitempty"`
	// Flag holds the value of the "flag" field.
	Flag string `json:"flag,omitempty"`
}

// scanValues returns the types for scanning values from sql.Rows.
func (*RequestLog) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case requestlog.FieldBody:
			values[i] = new([]byte)
		case requestlog.FieldID:
			values[i] = new(sql.NullInt64)
		case requestlog.FieldHeaders, requestlog.FieldFlag:
			values[i] = new(sql.NullString)
		case requestlog.FieldTime:
			values[i] = new(sql.NullTime)
		default:
			return nil, fmt.Errorf("unexpected column %q for type RequestLog", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the RequestLog fields.
func (rl *RequestLog) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case requestlog.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			rl.ID = int(value.Int64)
		case requestlog.FieldTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field time", values[i])
			} else if value.Valid {
				rl.Time = value.Time
			}
		case requestlog.FieldHeaders:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field headers", values[i])
			} else if value.Valid {
				rl.Headers = value.String
			}
		case requestlog.FieldBody:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field body", values[i])
			} else if value != nil {
				rl.Body = *value
			}
		case requestlog.FieldFlag:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field flag", values[i])
			} else if value.Valid {
				rl.Flag = value.String
			}
		}
	}
	return nil
}

// Update returns a builder for updating this RequestLog.
// Note that you need to call RequestLog.Unwrap() before calling this method if this RequestLog
// was returned from a transaction, and the transaction was committed or rolled back.
func (rl *RequestLog) Update() *RequestLogUpdateOne {
	return (&RequestLogClient{config: rl.config}).UpdateOne(rl)
}

// Unwrap unwraps the RequestLog entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (rl *RequestLog) Unwrap() *RequestLog {
	_tx, ok := rl.config.driver.(*txDriver)
	if !ok {
		panic("ent: RequestLog is not a transactional entity")
	}
	rl.config.driver = _tx.drv
	return rl
}

// String implements the fmt.Stringer.
func (rl *RequestLog) String() string {
	var builder strings.Builder
	builder.WriteString("RequestLog(")
	builder.WriteString(fmt.Sprintf("id=%v, ", rl.ID))
	builder.WriteString("time=")
	builder.WriteString(rl.Time.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("headers=")
	builder.WriteString(rl.Headers)
	builder.WriteString(", ")
	builder.WriteString("body=")
	builder.WriteString(fmt.Sprintf("%v", rl.Body))
	builder.WriteString(", ")
	builder.WriteString("flag=")
	builder.WriteString(rl.Flag)
	builder.WriteByte(')')
	return builder.String()
}

// RequestLogs is a parsable slice of RequestLog.
type RequestLogs []*RequestLog

func (rl RequestLogs) config(cfg config) {
	for _i := range rl {
		rl[_i].config = cfg
	}
}
