// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// ServiceProvider is the predicate function for serviceprovider builders.
type ServiceProvider func(*sql.Selector)
