// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// RequestLog is the predicate function for requestlog builders.
type RequestLog func(*sql.Selector)
